// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package genny

//FilterWithInt filter int type
func FilterWithInt(source []int, callback func(int) bool) []int {
	var out []int
	for _, element := range source {
		if callback(element) {
			out = append(out, element)
		}
	}
	return out
}

//FilterWithString filter string type
func FilterWithString(source []string, callback func(string) bool) []string {
	var out []string
	for _, element := range source {
		if callback(element) {
			out = append(out, element)
		}
	}
	return out
}

//FilterWithFloat32 filter float32 type
func FilterWithFloat32(source []float32, callback func(float32) bool) []float32 {
	var out []float32
	for _, element := range source {
		if callback(element) {
			out = append(out, element)
		}
	}
	return out
}
